export enum EProfileValidationError {
  INCORRECT_FIRST_LAST_NAME = 'INCORRECT_FIRST_LAST_NAME',
  INCORRECT_USERNAME = 'INCORRECT_USERNAME',
  INCORRECT_AGE = 'INCORRECT_AGE',
  INCORRECT_CITY = 'INCORRECT_CITY',
  INCORRECT_AVATAR = 'INCORRECT_AVATAR',
  NO_DATA = 'NO DATA',
  SERVER_ERROR = 'SERVER_ERROR',
}
