name: build, lint, test ts-ui
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn
      - name: build prod
        run: yarn build
        if: always()
      - name: lint
        run: yarn lint
        if: always()
      - name: lint css
        run: yarn lint:styles
      - name: unit test
        if: always()
        run: yarn test:unit
      #- name: build storybook
      #  run: yarn sb:build
      #  if: always()
      #- name: ui test
      #  run: yarn test:ui:ci
      #  if: always()
